import turtle
turtle = turtle.Turtle()
turtle.dot()
turtle.right(-45)
turtle.forward(141.5)
turtle.dot()
turtle.right(135)
turtle.forward(200)
turtle.dot()
turtle.right(135)
turtle.forward(283)
turtle.dot()
turtle.left(135)
turtle.forward(200)
turtle.dot()
turtle.left(135)
turtle.forward(283)
turtle.left(135)


turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.hideturtle()


#200,200, 283