import turtle
turtle = turtle.Turtle()
turtle.penup()
turtle.forward(-50)
turtle.pendown()
turtle.left(65)
turtle.forward(170)
turtle.right(130)

turtle.forward(170)
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.right(115)
turtle.forward(144)
turtle.right(140)
turtle.forward(94)
turtle.right(80)
turtle.forward(94)
turtle.right(140)
turtle.forward(140)
turtle.end_fill()
turtle.hideturtle()
